CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'isalgar'@'%' IDENTIFIED BY '12345';
GRANT ALL PRIVILEGES ON wordpress.* TO 'isalgar'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'test';
